<?php
/**
 * V1alphaGenerationApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stability.ai REST API
 *
 * Welcome to the Stability.ai REST API developer preview!  Please note, this is an beta version of our new REST API.  API operations use the following versioning scheme: - `/v*alpha*`: under development and the interface is subject to change - `/v*beta*`: interface is stable, preparing for production release - `/v*` interface is stable and ready for production workloads  Your DreamStudio API key will be required for authentication: [How to find your API key](https://platform.stability.ai/docs/getting-started/authentication)  If you have feedback or encounter any issues with the API, please reach out:   - [https://github.com/Stability-AI/REST-API](https://github.com/Stability-AI/REST-API)   - [https://discord.gg/stablediffusion #API channel](https://discord.com/channels/1002292111942635562/1042896447311454361)
 *
 * The version of the OpenAPI document: v1beta
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * V1alphaGenerationApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V1alphaGenerationApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'v1AlphaimageToImage' => [
            'multipart/form-data',
        ],
        'v1Alphamasking' => [
            'multipart/form-data',
        ],
        'v1AlphatextToImage' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1AlphaimageToImage
     *
     * image-to-image
     *
     * @param  string $engine_id engine_id (required)
     * @param  string $authorization authorization (required)
     * @param  \SplFileObject $init_image Initial image to use for the image-to-image generation (required)
     * @param  \OpenAPI\Client\Model\ImageToImageOptions $options options (required)
     * @param  string $accept accept (optional, default to 'application/json')
     * @param  string $organization Allows for requests to be scoped to an organization other than the user&#39;s default.  If not provided, the user&#39;s default organization will be used. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AlphaimageToImage'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v1AlphaimageToImage($engine_id, $authorization, $init_image, $options, $accept = 'application/json', $organization = null, string $contentType = self::contentTypes['v1AlphaimageToImage'][0])
    {
        $this->v1AlphaimageToImageWithHttpInfo($engine_id, $authorization, $init_image, $options, $accept, $organization, $contentType);
    }

    /**
     * Operation v1AlphaimageToImageWithHttpInfo
     *
     * image-to-image
     *
     * @param  string $engine_id (required)
     * @param  string $authorization (required)
     * @param  \SplFileObject $init_image Initial image to use for the image-to-image generation (required)
     * @param  \OpenAPI\Client\Model\ImageToImageOptions $options (required)
     * @param  string $accept (optional, default to 'application/json')
     * @param  string $organization Allows for requests to be scoped to an organization other than the user&#39;s default.  If not provided, the user&#39;s default organization will be used. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AlphaimageToImage'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AlphaimageToImageWithHttpInfo($engine_id, $authorization, $init_image, $options, $accept = 'application/json', $organization = null, string $contentType = self::contentTypes['v1AlphaimageToImage'][0])
    {
        $request = $this->v1AlphaimageToImageRequest($engine_id, $authorization, $init_image, $options, $accept, $organization, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\V1AlphaError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\V1AlphaError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\V1AlphaError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\V1AlphaError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1AlphaimageToImageAsync
     *
     * image-to-image
     *
     * @param  string $engine_id (required)
     * @param  string $authorization (required)
     * @param  \SplFileObject $init_image Initial image to use for the image-to-image generation (required)
     * @param  \OpenAPI\Client\Model\ImageToImageOptions $options (required)
     * @param  string $accept (optional, default to 'application/json')
     * @param  string $organization Allows for requests to be scoped to an organization other than the user&#39;s default.  If not provided, the user&#39;s default organization will be used. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AlphaimageToImage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AlphaimageToImageAsync($engine_id, $authorization, $init_image, $options, $accept = 'application/json', $organization = null, string $contentType = self::contentTypes['v1AlphaimageToImage'][0])
    {
        return $this->v1AlphaimageToImageAsyncWithHttpInfo($engine_id, $authorization, $init_image, $options, $accept, $organization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AlphaimageToImageAsyncWithHttpInfo
     *
     * image-to-image
     *
     * @param  string $engine_id (required)
     * @param  string $authorization (required)
     * @param  \SplFileObject $init_image Initial image to use for the image-to-image generation (required)
     * @param  \OpenAPI\Client\Model\ImageToImageOptions $options (required)
     * @param  string $accept (optional, default to 'application/json')
     * @param  string $organization Allows for requests to be scoped to an organization other than the user&#39;s default.  If not provided, the user&#39;s default organization will be used. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AlphaimageToImage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AlphaimageToImageAsyncWithHttpInfo($engine_id, $authorization, $init_image, $options, $accept = 'application/json', $organization = null, string $contentType = self::contentTypes['v1AlphaimageToImage'][0])
    {
        $returnType = '';
        $request = $this->v1AlphaimageToImageRequest($engine_id, $authorization, $init_image, $options, $accept, $organization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AlphaimageToImage'
     *
     * @param  string $engine_id (required)
     * @param  string $authorization (required)
     * @param  \SplFileObject $init_image Initial image to use for the image-to-image generation (required)
     * @param  \OpenAPI\Client\Model\ImageToImageOptions $options (required)
     * @param  string $accept (optional, default to 'application/json')
     * @param  string $organization Allows for requests to be scoped to an organization other than the user&#39;s default.  If not provided, the user&#39;s default organization will be used. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AlphaimageToImage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AlphaimageToImageRequest($engine_id, $authorization, $init_image, $options, $accept = 'application/json', $organization = null, string $contentType = self::contentTypes['v1AlphaimageToImage'][0])
    {

        // verify the required parameter 'engine_id' is set
        if ($engine_id === null || (is_array($engine_id) && count($engine_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $engine_id when calling v1AlphaimageToImage'
            );
        }

        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling v1AlphaimageToImage'
            );
        }

        // verify the required parameter 'init_image' is set
        if ($init_image === null || (is_array($init_image) && count($init_image) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $init_image when calling v1AlphaimageToImage'
            );
        }

        // verify the required parameter 'options' is set
        if ($options === null || (is_array($options) && count($options) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $options when calling v1AlphaimageToImage'
            );
        }




        $resourcePath = '/v1alpha/generation/{engine_id}/image-to-image';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($accept !== null) {
            $headerParams['Accept'] = ObjectSerializer::toHeaderValue($accept);
        }
        // header params
        if ($organization !== null) {
            $headerParams['Organization'] = ObjectSerializer::toHeaderValue($organization);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($engine_id !== null) {
            $resourcePath = str_replace(
                '{' . 'engine_id' . '}',
                ObjectSerializer::toPathValue($engine_id),
                $resourcePath
            );
        }

        // form params
        if ($init_image !== null) {
            $multipart = true;
            $formParams['init_image'] = [];
            $paramFiles = is_array($init_image) ? $init_image : [$init_image];
            foreach ($paramFiles as $paramFile) {
                $formParams['init_image'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }
        // form params
        if ($options !== null) {
            $formParams['options'] = ObjectSerializer::toFormValue($options);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1Alphamasking
     *
     * image-to-image/masking
     *
     * @param  string $engine_id engine_id (required)
     * @param  string $authorization authorization (required)
     * @param  \SplFileObject $init_image Initial image to use for the image-to-image generation (required)
     * @param  \OpenAPI\Client\Model\MaskingOptions $options options (required)
     * @param  string $accept accept (optional, default to 'application/json')
     * @param  string $organization Allows for requests to be scoped to an organization other than the user&#39;s default.  If not provided, the user&#39;s default organization will be used. (optional)
     * @param  \SplFileObject $mask_image Optional grayscale mask that allows for influence over which pixels are eligible for diffusion and at what strength. Must be the same dimensions as the &#x60;init_image&#x60;. Use the &#x60;mask_source&#x60; option to specify whether the white or black pixels should be inpainted. (Note: if you set &#x60;mask_source&#x60; to &#x60;INIT_IMAGE_ALPHA&#x60; you can omit the &#x60;mask_image&#x60; parameter.) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Alphamasking'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v1Alphamasking($engine_id, $authorization, $init_image, $options, $accept = 'application/json', $organization = null, $mask_image = null, string $contentType = self::contentTypes['v1Alphamasking'][0])
    {
        $this->v1AlphamaskingWithHttpInfo($engine_id, $authorization, $init_image, $options, $accept, $organization, $mask_image, $contentType);
    }

    /**
     * Operation v1AlphamaskingWithHttpInfo
     *
     * image-to-image/masking
     *
     * @param  string $engine_id (required)
     * @param  string $authorization (required)
     * @param  \SplFileObject $init_image Initial image to use for the image-to-image generation (required)
     * @param  \OpenAPI\Client\Model\MaskingOptions $options (required)
     * @param  string $accept (optional, default to 'application/json')
     * @param  string $organization Allows for requests to be scoped to an organization other than the user&#39;s default.  If not provided, the user&#39;s default organization will be used. (optional)
     * @param  \SplFileObject $mask_image Optional grayscale mask that allows for influence over which pixels are eligible for diffusion and at what strength. Must be the same dimensions as the &#x60;init_image&#x60;. Use the &#x60;mask_source&#x60; option to specify whether the white or black pixels should be inpainted. (Note: if you set &#x60;mask_source&#x60; to &#x60;INIT_IMAGE_ALPHA&#x60; you can omit the &#x60;mask_image&#x60; parameter.) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Alphamasking'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AlphamaskingWithHttpInfo($engine_id, $authorization, $init_image, $options, $accept = 'application/json', $organization = null, $mask_image = null, string $contentType = self::contentTypes['v1Alphamasking'][0])
    {
        $request = $this->v1AlphamaskingRequest($engine_id, $authorization, $init_image, $options, $accept, $organization, $mask_image, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\V1AlphaError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\V1AlphaError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\V1AlphaError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\V1AlphaError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1AlphamaskingAsync
     *
     * image-to-image/masking
     *
     * @param  string $engine_id (required)
     * @param  string $authorization (required)
     * @param  \SplFileObject $init_image Initial image to use for the image-to-image generation (required)
     * @param  \OpenAPI\Client\Model\MaskingOptions $options (required)
     * @param  string $accept (optional, default to 'application/json')
     * @param  string $organization Allows for requests to be scoped to an organization other than the user&#39;s default.  If not provided, the user&#39;s default organization will be used. (optional)
     * @param  \SplFileObject $mask_image Optional grayscale mask that allows for influence over which pixels are eligible for diffusion and at what strength. Must be the same dimensions as the &#x60;init_image&#x60;. Use the &#x60;mask_source&#x60; option to specify whether the white or black pixels should be inpainted. (Note: if you set &#x60;mask_source&#x60; to &#x60;INIT_IMAGE_ALPHA&#x60; you can omit the &#x60;mask_image&#x60; parameter.) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Alphamasking'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AlphamaskingAsync($engine_id, $authorization, $init_image, $options, $accept = 'application/json', $organization = null, $mask_image = null, string $contentType = self::contentTypes['v1Alphamasking'][0])
    {
        return $this->v1AlphamaskingAsyncWithHttpInfo($engine_id, $authorization, $init_image, $options, $accept, $organization, $mask_image, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AlphamaskingAsyncWithHttpInfo
     *
     * image-to-image/masking
     *
     * @param  string $engine_id (required)
     * @param  string $authorization (required)
     * @param  \SplFileObject $init_image Initial image to use for the image-to-image generation (required)
     * @param  \OpenAPI\Client\Model\MaskingOptions $options (required)
     * @param  string $accept (optional, default to 'application/json')
     * @param  string $organization Allows for requests to be scoped to an organization other than the user&#39;s default.  If not provided, the user&#39;s default organization will be used. (optional)
     * @param  \SplFileObject $mask_image Optional grayscale mask that allows for influence over which pixels are eligible for diffusion and at what strength. Must be the same dimensions as the &#x60;init_image&#x60;. Use the &#x60;mask_source&#x60; option to specify whether the white or black pixels should be inpainted. (Note: if you set &#x60;mask_source&#x60; to &#x60;INIT_IMAGE_ALPHA&#x60; you can omit the &#x60;mask_image&#x60; parameter.) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Alphamasking'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AlphamaskingAsyncWithHttpInfo($engine_id, $authorization, $init_image, $options, $accept = 'application/json', $organization = null, $mask_image = null, string $contentType = self::contentTypes['v1Alphamasking'][0])
    {
        $returnType = '';
        $request = $this->v1AlphamaskingRequest($engine_id, $authorization, $init_image, $options, $accept, $organization, $mask_image, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1Alphamasking'
     *
     * @param  string $engine_id (required)
     * @param  string $authorization (required)
     * @param  \SplFileObject $init_image Initial image to use for the image-to-image generation (required)
     * @param  \OpenAPI\Client\Model\MaskingOptions $options (required)
     * @param  string $accept (optional, default to 'application/json')
     * @param  string $organization Allows for requests to be scoped to an organization other than the user&#39;s default.  If not provided, the user&#39;s default organization will be used. (optional)
     * @param  \SplFileObject $mask_image Optional grayscale mask that allows for influence over which pixels are eligible for diffusion and at what strength. Must be the same dimensions as the &#x60;init_image&#x60;. Use the &#x60;mask_source&#x60; option to specify whether the white or black pixels should be inpainted. (Note: if you set &#x60;mask_source&#x60; to &#x60;INIT_IMAGE_ALPHA&#x60; you can omit the &#x60;mask_image&#x60; parameter.) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1Alphamasking'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AlphamaskingRequest($engine_id, $authorization, $init_image, $options, $accept = 'application/json', $organization = null, $mask_image = null, string $contentType = self::contentTypes['v1Alphamasking'][0])
    {

        // verify the required parameter 'engine_id' is set
        if ($engine_id === null || (is_array($engine_id) && count($engine_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $engine_id when calling v1Alphamasking'
            );
        }

        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling v1Alphamasking'
            );
        }

        // verify the required parameter 'init_image' is set
        if ($init_image === null || (is_array($init_image) && count($init_image) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $init_image when calling v1Alphamasking'
            );
        }

        // verify the required parameter 'options' is set
        if ($options === null || (is_array($options) && count($options) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $options when calling v1Alphamasking'
            );
        }





        $resourcePath = '/v1alpha/generation/{engine_id}/image-to-image/masking';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($accept !== null) {
            $headerParams['Accept'] = ObjectSerializer::toHeaderValue($accept);
        }
        // header params
        if ($organization !== null) {
            $headerParams['Organization'] = ObjectSerializer::toHeaderValue($organization);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($engine_id !== null) {
            $resourcePath = str_replace(
                '{' . 'engine_id' . '}',
                ObjectSerializer::toPathValue($engine_id),
                $resourcePath
            );
        }

        // form params
        if ($init_image !== null) {
            $multipart = true;
            $formParams['init_image'] = [];
            $paramFiles = is_array($init_image) ? $init_image : [$init_image];
            foreach ($paramFiles as $paramFile) {
                $formParams['init_image'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }
        // form params
        if ($mask_image !== null) {
            $multipart = true;
            $formParams['mask_image'] = [];
            $paramFiles = is_array($mask_image) ? $mask_image : [$mask_image];
            foreach ($paramFiles as $paramFile) {
                $formParams['mask_image'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }
        // form params
        if ($options !== null) {
            $formParams['options'] = ObjectSerializer::toFormValue($options);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AlphatextToImage
     *
     * text-to-image
     *
     * @param  string $engine_id engine_id (required)
     * @param  string $authorization authorization (required)
     * @param  \OpenAPI\Client\Model\V1AlphaTextToImageRequestBody $v1_alpha_text_to_image_request_body v1_alpha_text_to_image_request_body (required)
     * @param  string $accept accept (optional, default to 'application/json')
     * @param  string $organization Allows for requests to be scoped to an organization other than the user&#39;s default.  If not provided, the user&#39;s default organization will be used. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AlphatextToImage'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Image[]|\OpenAPI\Client\Model\V1AlphaError|\OpenAPI\Client\Model\V1AlphaError|\OpenAPI\Client\Model\V1AlphaError|\OpenAPI\Client\Model\V1AlphaError
     */
    public function v1AlphatextToImage($engine_id, $authorization, $v1_alpha_text_to_image_request_body, $accept = 'application/json', $organization = null, string $contentType = self::contentTypes['v1AlphatextToImage'][0])
    {
        list($response) = $this->v1AlphatextToImageWithHttpInfo($engine_id, $authorization, $v1_alpha_text_to_image_request_body, $accept, $organization, $contentType);
        return $response;
    }

    /**
     * Operation v1AlphatextToImageWithHttpInfo
     *
     * text-to-image
     *
     * @param  string $engine_id (required)
     * @param  string $authorization (required)
     * @param  \OpenAPI\Client\Model\V1AlphaTextToImageRequestBody $v1_alpha_text_to_image_request_body (required)
     * @param  string $accept (optional, default to 'application/json')
     * @param  string $organization Allows for requests to be scoped to an organization other than the user&#39;s default.  If not provided, the user&#39;s default organization will be used. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AlphatextToImage'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Image[]|\OpenAPI\Client\Model\V1AlphaError|\OpenAPI\Client\Model\V1AlphaError|\OpenAPI\Client\Model\V1AlphaError|\OpenAPI\Client\Model\V1AlphaError, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AlphatextToImageWithHttpInfo($engine_id, $authorization, $v1_alpha_text_to_image_request_body, $accept = 'application/json', $organization = null, string $contentType = self::contentTypes['v1AlphatextToImage'][0])
    {
        $request = $this->v1AlphatextToImageRequest($engine_id, $authorization, $v1_alpha_text_to_image_request_body, $accept, $organization, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\Image[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\Image[]' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Image[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\OpenAPI\Client\Model\V1AlphaError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\V1AlphaError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\V1AlphaError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\OpenAPI\Client\Model\V1AlphaError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\V1AlphaError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\V1AlphaError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\OpenAPI\Client\Model\V1AlphaError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\V1AlphaError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\V1AlphaError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\OpenAPI\Client\Model\V1AlphaError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\V1AlphaError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\V1AlphaError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\Image[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Image[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\V1AlphaError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\V1AlphaError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\V1AlphaError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\V1AlphaError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1AlphatextToImageAsync
     *
     * text-to-image
     *
     * @param  string $engine_id (required)
     * @param  string $authorization (required)
     * @param  \OpenAPI\Client\Model\V1AlphaTextToImageRequestBody $v1_alpha_text_to_image_request_body (required)
     * @param  string $accept (optional, default to 'application/json')
     * @param  string $organization Allows for requests to be scoped to an organization other than the user&#39;s default.  If not provided, the user&#39;s default organization will be used. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AlphatextToImage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AlphatextToImageAsync($engine_id, $authorization, $v1_alpha_text_to_image_request_body, $accept = 'application/json', $organization = null, string $contentType = self::contentTypes['v1AlphatextToImage'][0])
    {
        return $this->v1AlphatextToImageAsyncWithHttpInfo($engine_id, $authorization, $v1_alpha_text_to_image_request_body, $accept, $organization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AlphatextToImageAsyncWithHttpInfo
     *
     * text-to-image
     *
     * @param  string $engine_id (required)
     * @param  string $authorization (required)
     * @param  \OpenAPI\Client\Model\V1AlphaTextToImageRequestBody $v1_alpha_text_to_image_request_body (required)
     * @param  string $accept (optional, default to 'application/json')
     * @param  string $organization Allows for requests to be scoped to an organization other than the user&#39;s default.  If not provided, the user&#39;s default organization will be used. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AlphatextToImage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AlphatextToImageAsyncWithHttpInfo($engine_id, $authorization, $v1_alpha_text_to_image_request_body, $accept = 'application/json', $organization = null, string $contentType = self::contentTypes['v1AlphatextToImage'][0])
    {
        $returnType = '\OpenAPI\Client\Model\Image[]';
        $request = $this->v1AlphatextToImageRequest($engine_id, $authorization, $v1_alpha_text_to_image_request_body, $accept, $organization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AlphatextToImage'
     *
     * @param  string $engine_id (required)
     * @param  string $authorization (required)
     * @param  \OpenAPI\Client\Model\V1AlphaTextToImageRequestBody $v1_alpha_text_to_image_request_body (required)
     * @param  string $accept (optional, default to 'application/json')
     * @param  string $organization Allows for requests to be scoped to an organization other than the user&#39;s default.  If not provided, the user&#39;s default organization will be used. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AlphatextToImage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AlphatextToImageRequest($engine_id, $authorization, $v1_alpha_text_to_image_request_body, $accept = 'application/json', $organization = null, string $contentType = self::contentTypes['v1AlphatextToImage'][0])
    {

        // verify the required parameter 'engine_id' is set
        if ($engine_id === null || (is_array($engine_id) && count($engine_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $engine_id when calling v1AlphatextToImage'
            );
        }

        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling v1AlphatextToImage'
            );
        }

        // verify the required parameter 'v1_alpha_text_to_image_request_body' is set
        if ($v1_alpha_text_to_image_request_body === null || (is_array($v1_alpha_text_to_image_request_body) && count($v1_alpha_text_to_image_request_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $v1_alpha_text_to_image_request_body when calling v1AlphatextToImage'
            );
        }




        $resourcePath = '/v1alpha/generation/{engine_id}/text-to-image';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($accept !== null) {
            $headerParams['Accept'] = ObjectSerializer::toHeaderValue($accept);
        }
        // header params
        if ($organization !== null) {
            $headerParams['Organization'] = ObjectSerializer::toHeaderValue($organization);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($engine_id !== null) {
            $resourcePath = str_replace(
                '{' . 'engine_id' . '}',
                ObjectSerializer::toPathValue($engine_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'image/png', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($v1_alpha_text_to_image_request_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($v1_alpha_text_to_image_request_body));
            } else {
                $httpBody = $v1_alpha_text_to_image_request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
