<?php
/**
 * Sampler
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stability.ai REST API
 *
 * Welcome to the Stability.ai REST API developer preview!  Please note, this is an beta version of our new REST API.  API operations use the following versioning scheme: - `/v*alpha*`: under development and the interface is subject to change - `/v*beta*`: interface is stable, preparing for production release - `/v*` interface is stable and ready for production workloads  Your DreamStudio API key will be required for authentication: [How to find your API key](https://platform.stability.ai/docs/getting-started/authentication)  If you have feedback or encounter any issues with the API, please reach out:   - [https://github.com/Stability-AI/REST-API](https://github.com/Stability-AI/REST-API)   - [https://discord.gg/stablediffusion #API channel](https://discord.com/channels/1002292111942635562/1042896447311454361)
 *
 * The version of the OpenAPI document: v1beta
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Sampler Class Doc Comment
 *
 * @category Class
 * @description Which sampler to use for the diffusion process. If this value is omitted we&#39;ll automatically select an appropriate sampler for you.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Sampler
{
    /**
     * Possible values of this enum
     */
    public const DDIM = 'DDIM';

    public const DDPM = 'DDPM';

    public const K_DPMPP_2_M = 'K_DPMPP_2M';

    public const K_DPMPP_2_S_ANCESTRAL = 'K_DPMPP_2S_ANCESTRAL';

    public const K_DPM_2 = 'K_DPM_2';

    public const K_DPM_2_ANCESTRAL = 'K_DPM_2_ANCESTRAL';

    public const K_EULER = 'K_EULER';

    public const K_EULER_ANCESTRAL = 'K_EULER_ANCESTRAL';

    public const K_HEUN = 'K_HEUN';

    public const K_LMS = 'K_LMS';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DDIM,
            self::DDPM,
            self::K_DPMPP_2_M,
            self::K_DPMPP_2_S_ANCESTRAL,
            self::K_DPM_2,
            self::K_DPM_2_ANCESTRAL,
            self::K_EULER,
            self::K_EULER_ANCESTRAL,
            self::K_HEUN,
            self::K_LMS
        ];
    }
}


